language: java

cache:
  directories:
    - $HOME/.m2

# Cobertura is not supported in JDK11 so you must downgrade the JDK that Travis uses if you want to use Cobertura with Travis.
# See https://github.com/cobertura/cobertura/issues/381
jdk:
  - openjdk8

after_success:
  - mvn clean test jacoco:report coveralls:report
